server:
  port: 9999 
  contextPath: /uaa
spring:
  jpa:
     database: POSTGRESQL
     show-sql: true
     hibernate:
       ddl-auto: update
  datasource:
     driver-class-name: org.postgresql.Driver
     platform: postgres
     url: jdbc:postgresql://localhost:5432/security_db
     username: postgres
     password: postgres
